#pragma once
#ifndef MAP_H //Makes sure to define the header if it is not defined already
#define MAP_H
#endif
#include <iostream>
#include <vector>
#include <SFML/Graphics.hpp>
#include "Drawable_calculations.h"

class Map
{
private:
	int map_id = -1; //the map id is generated by the user and is what the user sees that distinguishes each map, in a future iteration for this program, it may be better to sort each map by its it in ascending order when each map is listed
	int vec_pos = -1; //the index that this map is located in Editor::maps_vec
public:
	sf::Texture map_texture; //image used by map_sprite
	sf::Sprite map_sprite; //the sprite used for a map's background image
	std::vector<sf::RectangleShape> collision_vectors; //rectangles that prevent the player from moving when the player sprites bounding box collides with one of the sf::RectangleShapes stored in this std::vector
	std::vector<int> map_trigger_ids; //map ids associated with each map trigger
	std::vector<int> map_trigger_vec_pos; //map vector positions associated with each map trigger
	std::vector<sf::RectangleShape> map_triggers; //sf::RectangleShapes that change the current map when the player collides with them, currently are buggy and do not work, I was unable to fix this due to time constraints
	Map(int set_map_id) //the constructor for this class requires a map id to be set
	{
		map_id = set_map_id;
	}
	void change_image(std::string &dir); //handles the changing of the map image texture
	void render_map(sf::RenderWindow& window); //draws the map image sprite
	void setID(int set_map_id); //sets the private member map_id
	int get_map_id(); //returns the private member map_id
	int get_vec_pos(); //returns the private member vec_pos
	void set_map_id(int new_id); //sets the private member map_id
	void set_vec_pos(int new_pos); //sets the private member vec_pos
	void render_vectors(sf::RenderWindow &window); //renders all map trigger and collision vectors for use in the editor
};